#!/usr/bin/env python3

import sys

from PyQt5 import QtCore, QtWidgets

from src.mainw import MainWin
from src.util import loadOrNew

# Windows home + "AppData\Local\86BoxManPy\"
# Linux home + ".config/86BoxManPy/"
# Mac home + "Library/Application Support/86BoxManPy/86BoxManPy/"

if __name__ == "__main__":
    QtCore.QCoreApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling, True)
    QtCore.QCoreApplication.setAttribute(QtCore.Qt.AA_UseHighDpiPixmaps, True)
    app = QtWidgets.QApplication(sys.argv)

    datadict = loadOrNew()
    MainWindow = QtWidgets.QMainWindow()
    MainWindow.ui = MainWin()
    MainWindow.ui.setupWin(MainWindow, datadict)
    MainWindow.show()
    sys.exit(app.exec_())
